# Generated by Django 3.0.5 on 2020-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PrId', models.AutoField(primary_key=True, serialize=False)),
                ('ChinaPr', models.CharField(default='', max_length=100)),
                ('IndPr1', models.CharField(default='', max_length=100)),
                ('IndPr2', models.CharField(default='', max_length=100)),
                ('IndPr3', models.CharField(default='', max_length=100)),
                ('WorPr1', models.CharField(default='', max_length=100)),
                ('WorPr2', models.CharField(default='', max_length=100)),
                ('WorPr3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
