# Generated by Django 3.0.5 on 2020-06-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boycott', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='IndPr3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='WorPr3',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
